name: Test the plugin

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12"]
        xdist_version: [3.6.1]
        pytest_version: [8.1.1]
    name: Test against Python and xdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python_version }}'
      - run: pip install '${{ matrix.xdist_version }}' '${{ matrix.pytest_version }}' .
      - run: pytest tests
